# Generated by Django 4.2.4 on 2023-08-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='the publisher description.', max_length=50)),
                ('Telefono', models.IntegerField(help_text='the publisher talle.')),
                ('Direccion', models.CharField(help_text='the publisher talle.', max_length=50)),
                ('Saldo', models.FloatField(help_text='the publisher precioCompra.')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoProducto', models.CharField(help_text='the name of publisher.', max_length=50)),
                ('Descripcion', models.CharField(help_text='the publisher description.', max_length=50)),
                ('Talle', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50)),
                ('Color', models.CharField(help_text='the publisher color.', max_length=50)),
                ('Marca', models.CharField(help_text='the publisher marca.', max_length=50)),
                ('PrecioCompra', models.FloatField(help_text='the publisher precioCompra.')),
                ('PrecioVenta', models.FloatField(help_text='the publisher PrecioVenta.')),
                ('Stock', models.IntegerField(help_text='the publisher stock.')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='the publisher description.', max_length=50)),
                ('Telefono', models.IntegerField(help_text='the publisher talle.')),
                ('Localidad', models.CharField(help_text='the publisher talle.', max_length=50)),
                ('Email', models.CharField(help_text='the publisher description.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='the publisher description.', max_length=50)),
                ('Telefono', models.IntegerField(help_text='the publisher talle.')),
                ('Direccion', models.CharField(help_text='the publisher talle.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoVenta', models.CharField(help_text='the publisher description.', max_length=50)),
                ('TipoPago', models.CharField(help_text='the publisher description.', max_length=50)),
                ('Total', models.FloatField(help_text='the publisher talle.')),
                ('Fecha', models.DateField(help_text='the publisher description.')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cliente')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
                ('Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talle', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.proveedor')),
            ],
        ),
    ]
