# Generated by Django 4.2.4 on 2023-09-19 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compraprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.compra')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
            ],
        ),
    ]
