# Generated by Django 4.2.4 on 2023-09-27 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0004_remove_compra_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Talle',
        ),
        migrations.AddField(
            model_name='compra',
            name='Fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
