# Generated by Django 4.2.4 on 2023-10-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0005_remove_compra_talle_compra_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['TipoProducto', 'Descripcion']},
        ),
    ]
