# Generated by Django 4.2.4 on 2023-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraprod',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compraprod',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventaprod',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventaprod',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
