# Generated by Django 4.2.4 on 2023-11-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0007_compraprod_cantidad_compraprod_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
