# Generated by Django 4.2.4 on 2023-11-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0008_alter_ventas_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Total',
        ),
    ]
