# Generated by Django 4.2.4 on 2024-01-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
