# Generated by Django 4.2.4 on 2024-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0013_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraprod',
            old_name='Total',
            new_name='SubTotal',
        ),
        migrations.RenameField(
            model_name='ventaprod',
            old_name='Total',
            new_name='SubTotal',
        ),
        migrations.AddField(
            model_name='compra',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
